# Generated by Django 4.2.7 on 2025-03-20 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("adventure", "0002_scenario_choice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="scenario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choices",
                to="adventure.scenario",
            ),
        ),
    ]
